# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5d8c8b34bce4e57eb9d7d60f72021cbb0cf7916a1306a3384c1d1f8b4c8f525a407932718d325de83aee7f1d1814d8db522c6e1a08024b21752e7cda039690

test:
  secret_key_base: e76cafb4d2f959a6983a9426649ee90326daf17217f323512298284f4cc453ed9ea70ff907197e2f7fbc8da52e11c88ea435fca4b78ab1ca591af01566c73f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
